eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false  #是否将自己注册到eureka sever,由于本身现在就是eureka所以为false
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka2
server:
  port: 8762