eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  #  register-with-eureka: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka
  profiles: eureka1
server:
  port: 8761